// layout.tsx er rodlayoutet for hele appen — det der altid vises uanset hvilken side man er på.
// Her pakkes alt ind i Providers (login, biler, favoritter) og ScreenLayout (navigation og struktur).
import "./globals.css";
import Providers from "@/components/Providers";
import ScreenLayout from "@/components/ScreenLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.png", type: "image/png" }],
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full" suppressHydrationWarning>
        <Providers>
          <ScreenLayout>{children}</ScreenLayout>
        </Providers>
      </body>
    </html>
  );
}