import "./globals.css";
import Providers from "@/components/Providers";
import ScreenLayout from "@/components/ScreenLayout";
import { VehiclesProvider } from "@/context/VehiclesContext";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.png", type: "image/png" }],
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full" suppressHydrationWarning>
        <Providers>
          <AuthProvider>
            <VehiclesProvider>
              <ScreenLayout>{children}</ScreenLayout>
            </VehiclesProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}