// layout.tsx – rod-layout for hele appen.
// metadata: definerer sidetitel, beskrivelse og favikon til browserfanen.
// RootLayout: omslutter alle sider med Providers (auth, køretøjer, favoritter mv.)
// og ScreenLayout (mobil-ramme med baggrundsgradient og fast bredde).
// children: indeholder den aktuelle side som Next.js injicerer automatisk.

import "./globals.css";
import Providers from "@/components/layout/Providers";
import ScreenLayout from "@/components/layout/ScreenLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.png", type: "image/png" }],
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full" suppressHydrationWarning>
        <Providers>
          <ScreenLayout>{children}</ScreenLayout>
        </Providers>
      </body>
    </html>
  );
}